# Generated by Django 5.1.5 on 2025-08-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('hourly_pay', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
