# Generated by Django 5.1.5 on 2025-08-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
    ]
